---
title: Tamara Lindsay
timezone: America/New_York
collections:
  portfolio:
    title: Portfolio
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: portfolio
  values:
    images:
    - ''
    colors:
    - ''
    - ''
    roles:
    - ''
description: Fashion and jewelry designer
url: http://www.tamaralindsay.com
permalink: pretty
exclude:
- Gruntfile.js
- webpack.config.js
- Gemfile.lock
- package.json
- README*
- node_modules
- ".gitignore"
- assets/scripts/src
gems:
- jekyll-seo-tag
- jekyll-sitemap
sass:
  sass_dir: assets/styles/
  style: compressed
menu:
- url: https://www.linkedin.com/in/tamaralindsay
  title: LinkedIn
- url: mailto:tamaralindsay29@gmail.com
  title: Email
